# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy

policy:
  - template: [000-bug-report.yml, 001-feature-request.yml]
    section:
      - id: [mc-version]
        block-list: ['Both', 'Any']
        label:
          - name: '1.20'
            keys: ['1.20.1 Forge']

          - name: '1.21'
            keys: ['1.21.1 NeoForge']
