blank_issues_enabled: false
contact_links:
  - name: GregTech CEu Discord
    url: https://discord.gg/bWSWuYvURP
    about: GTMogs doesn't have it's own discord, but since it just uses GTceu's oregen you can go there if you need help with oregen.
