# Manages labels on new issues
name: Retroactively apply Issue Labels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  label-all:
    runs-on: ubuntu-latest
    permissions:
      issues: write # IDK if this is needed to run manage-issue-labels, but it doesn't hurt so
      actions: write
    steps:
      - name: Labelifier
        uses: actions/github-script@v7
        id: label-em
        with:
          script: |
            github.paginate(github.rest.issues.listForRepo, {
              owner: "GregTechCEu",
              repo: "GregTech-Modern",
            }).then((issues) => {
              // issues is an array of all issue objects
              issues.forEach((issue) => {
                if (issue.pull_request != undefined) {
                    // if it's a pull request, skip it.
                    return;
                }
                octokit.rest.actions.createWorkflowDispatch({
                  owner: "GregTechCEu",
                  repo: "GregTech-Modern",
                  workflow_id: "manage-issue-labels",
                  ref: ${{ github.ref }},
                  inputs: {
                    issue_number: issue.body
                  }
                });
              });
            });
